spring:

  # .env import
  config:
    import: optional:file:./.env[.properties]

  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}

  # Spring Data JPA
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타냄
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가

# logging
logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
      hibernate:
        sql: debug
        type.descriptor.sql: trace # 파라미터 값 추가
        sql.results.internal.ResultsHelper: INFO # OneToMany 조회 관련 로그 숨김
    p6spy:

# p6spy log
decorator:
  datasource:
    p6spy:
      enable-logging: false

# promethues
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  server:
    port: ${SECRET_PORT}
    base-path: ${SECRET_PATH}