#!/bin/sh

stagedFiles=$(git diff --staged --name-only)

echo "Running SpotlessApply..."
./gradlew spotlessApply --daemon

for file in $stagedFiles; do
  if test -f "$file"; then
    git add "$file";
  fi
done
